name: borf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
#  - _libgcc_mutex=0.1
#  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi
  - charset-normalizer=2.1.1
  - cryptography=37.0.2
#  - cudatoolkit=11.6.0
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - idna=3.3
#  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
#  - ld_impl_linux-64=2.38
  - libffi
#  - libgcc-ng=11.2.0
#  - libgomp=11.2.0
  - libiconv=1.17
  - libpng=1.6.37
#  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
#  - mkl=2021.4.0
#  - mkl-service=2.4.0
#  - mkl_fft=1.3.1
#  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.6
  - numpy=1.23.1
  - numpy-base=1.23.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - pillow=8.2.0
  - pip=22.1.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.13
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.0
  - pip:
      - attrdict==2.0.1
      - cycler==0.11.0
      - fonttools==4.37.1
      - jinja2==3.1.2
      - joblib==1.1.0
      - kiwisolver==1.4.4
      - markupsafe==2.1.1
      - matplotlib==3.5.3
      - networkx==2.8.6
      - packaging==21.3
      - pandas==1.4.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.2.1
      - scikit-learn==1.1.2
      - scipy==1.9.1
      - threadpoolctl==3.1.0
      - torch-geometric==2.1.0.post1
      - torch-scatter==2.0.9
      - torch-sparse==0.6.15
      - tqdm==4.64.1